### PR TITLE
All resources created with parameters

### PR DESCRIPTION
**Pull request by gautam232019**
All the resources for the user story 1,2,3 which are needed are there in the template.json file for IAAC.

### CODE REVIEW

**Review by rohatginishant — CHANGES_REQUESTED** [review]
Add dropdown for SystemTypes for VM .

**Review by Pratyush-Misra — CHANGES_REQUESTED** [review]
Add user input for CIDR specifications

**Review by rohatginishant — APPROVED** [review]
Looks Good !

**Review by Pratyush-Misra — APPROVED** [review]
This seems good. I think we might need to rearrange the parameters.

**Pull request merged**
